// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: carabiner/signer/v1/identity.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Identity captures a signer identity. An identity can one of:
//
//	a) A sigstore identity
//	b) A key
//	c) A reference to an identity defined outside the policy
//	d) A SPIFFE identity
//
// The variant fields describe the signer ("who").
//
// The matchers slice and per-variant *_match convenience fields describe
// how policy matches against the signer ("how").
//
// In general:
// Verified-side Identity leaves matcher fields empty;
// Policy-side Identity populates them as needed.
type Identity struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sigstore *IdentitySigstore      `protobuf:"bytes,2,opt,name=sigstore,proto3,oneof" json:"sigstore,omitempty"`
	Key      *IdentityKey           `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Ref      *IdentityRef           `protobuf:"bytes,4,opt,name=ref,proto3,oneof" json:"ref,omitempty"`
	Spiffe   *IdentitySpiffe        `protobuf:"bytes,5,opt,name=spiffe,proto3,oneof" json:"spiffe,omitempty"`
	// Canonical policy-side matcher slice. Each Matcher targets a
	// sub-field of whichever variant is set. Verified-side Identity
	// leaves this empty.
	Matchers      []*Matcher `protobuf:"bytes,10,rep,name=matchers,proto3" json:"matchers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Identity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Identity) GetSigstore() *IdentitySigstore {
	if x != nil {
		return x.Sigstore
	}
	return nil
}

func (x *Identity) GetKey() *IdentityKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Identity) GetRef() *IdentityRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Identity) GetSpiffe() *IdentitySpiffe {
	if x != nil {
		return x.Spiffe
	}
	return nil
}

func (x *Identity) GetMatchers() []*Matcher {
	if x != nil {
		return x.Matchers
	}
	return nil
}

// IdentitySigstore represents the identity data in a Fulcio cert.
type IdentitySigstore struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Mode     *string                `protobuf:"bytes,1,opt,name=mode,proto3,oneof" json:"mode,omitempty"`   // exact | regexp (legacy ti be removed, prefer *_match)
	Issuer   string                 `protobuf:"bytes,2,opt,name=issuer,proto3" json:"issuer,omitempty"`     // https://accounts.google.com
	Identity string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"` //  "identity": "puerco@gmail.com"
	// Convenience per-field matchers. When set, participate in the
	// virtual matcher union alongside the legacy Mode/Issuer/Identity
	// fields and the outer Matcher slice.
	IssuerMatch   *StringMatcher `protobuf:"bytes,4,opt,name=issuer_match,json=issuerMatch,proto3" json:"issuer_match,omitempty"`
	IdentityMatch *StringMatcher `protobuf:"bytes,5,opt,name=identity_match,json=identityMatch,proto3" json:"identity_match,omitempty"`
	// Has no legacy form; pin via source_repository_uri_match.
	SourceRepositoryUri      string         `protobuf:"bytes,6,opt,name=source_repository_uri,json=sourceRepositoryUri,proto3" json:"source_repository_uri,omitempty"` // OID 1.3.6.1.4.1.57264.1.12
	SourceRepositoryUriMatch *StringMatcher `protobuf:"bytes,7,opt,name=source_repository_uri_match,json=sourceRepositoryUriMatch,proto3" json:"source_repository_uri_match,omitempty"`
	// The workflow the certificate was issued for (for a reusable
	// workflow, the calling workflow). Has no legacy form; pin via
	// build_config_uri_match.
	BuildConfigUri      string         `protobuf:"bytes,8,opt,name=build_config_uri,json=buildConfigUri,proto3" json:"build_config_uri,omitempty"` // OID 1.3.6.1.4.1.57264.1.18
	BuildConfigUriMatch *StringMatcher `protobuf:"bytes,9,opt,name=build_config_uri_match,json=buildConfigUriMatch,proto3" json:"build_config_uri_match,omitempty"`
	// The event that triggered the run, for example release or push. Has
	// no legacy form; pin via build_trigger_match.
	BuildTrigger      string         `protobuf:"bytes,10,opt,name=build_trigger,json=buildTrigger,proto3" json:"build_trigger,omitempty"` // OID 1.3.6.1.4.1.57264.1.20
	BuildTriggerMatch *StringMatcher `protobuf:"bytes,11,opt,name=build_trigger_match,json=buildTriggerMatch,proto3" json:"build_trigger_match,omitempty"`
	// The git ref the run was for, for example refs/tags/v1.2.3. Has no
	// legacy form; pin via source_repository_ref_match.
	SourceRepositoryRef      string         `protobuf:"bytes,12,opt,name=source_repository_ref,json=sourceRepositoryRef,proto3" json:"source_repository_ref,omitempty"` // OID 1.3.6.1.4.1.57264.1.14
	SourceRepositoryRefMatch *StringMatcher `protobuf:"bytes,13,opt,name=source_repository_ref_match,json=sourceRepositoryRefMatch,proto3" json:"source_repository_ref_match,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *IdentitySigstore) Reset() {
	*x = IdentitySigstore{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySigstore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySigstore) ProtoMessage() {}

func (x *IdentitySigstore) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySigstore.ProtoReflect.Descriptor instead.
func (*IdentitySigstore) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *IdentitySigstore) GetMode() string {
	if x != nil && x.Mode != nil {
		return *x.Mode
	}
	return ""
}

func (x *IdentitySigstore) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *IdentitySigstore) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *IdentitySigstore) GetIssuerMatch() *StringMatcher {
	if x != nil {
		return x.IssuerMatch
	}
	return nil
}

func (x *IdentitySigstore) GetIdentityMatch() *StringMatcher {
	if x != nil {
		return x.IdentityMatch
	}
	return nil
}

func (x *IdentitySigstore) GetSourceRepositoryUri() string {
	if x != nil {
		return x.SourceRepositoryUri
	}
	return ""
}

func (x *IdentitySigstore) GetSourceRepositoryUriMatch() *StringMatcher {
	if x != nil {
		return x.SourceRepositoryUriMatch
	}
	return nil
}

func (x *IdentitySigstore) GetBuildConfigUri() string {
	if x != nil {
		return x.BuildConfigUri
	}
	return ""
}

func (x *IdentitySigstore) GetBuildConfigUriMatch() *StringMatcher {
	if x != nil {
		return x.BuildConfigUriMatch
	}
	return nil
}

func (x *IdentitySigstore) GetBuildTrigger() string {
	if x != nil {
		return x.BuildTrigger
	}
	return ""
}

func (x *IdentitySigstore) GetBuildTriggerMatch() *StringMatcher {
	if x != nil {
		return x.BuildTriggerMatch
	}
	return nil
}

func (x *IdentitySigstore) GetSourceRepositoryRef() string {
	if x != nil {
		return x.SourceRepositoryRef
	}
	return ""
}

func (x *IdentitySigstore) GetSourceRepositoryRefMatch() *StringMatcher {
	if x != nil {
		return x.SourceRepositoryRefMatch
	}
	return nil
}

// IdentityKey registers the data of a key used to sign attestations.
type IdentityKey struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                           // Key ID
	Type               string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                                       // Identity type
	Data               string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                                                       // Public key data
	SigningFingerprint string                 `protobuf:"bytes,4,opt,name=signing_fingerprint,json=signingFingerprint,proto3" json:"signing_fingerprint,omitempty"` // Fingerprint of the signing subkey
	// Convenience per-field matchers. No data_match: PEM blobs aren't
	// pattern-matched; pin via id_match on the derived fingerprint.
	IdMatch                 *StringMatcher `protobuf:"bytes,5,opt,name=id_match,json=idMatch,proto3" json:"id_match,omitempty"`
	TypeMatch               *StringMatcher `protobuf:"bytes,6,opt,name=type_match,json=typeMatch,proto3" json:"type_match,omitempty"`
	SigningFingerprintMatch *StringMatcher `protobuf:"bytes,7,opt,name=signing_fingerprint_match,json=signingFingerprintMatch,proto3" json:"signing_fingerprint_match,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *IdentityKey) Reset() {
	*x = IdentityKey{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityKey) ProtoMessage() {}

func (x *IdentityKey) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityKey.ProtoReflect.Descriptor instead.
func (*IdentityKey) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *IdentityKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IdentityKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IdentityKey) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *IdentityKey) GetSigningFingerprint() string {
	if x != nil {
		return x.SigningFingerprint
	}
	return ""
}

func (x *IdentityKey) GetIdMatch() *StringMatcher {
	if x != nil {
		return x.IdMatch
	}
	return nil
}

func (x *IdentityKey) GetTypeMatch() *StringMatcher {
	if x != nil {
		return x.TypeMatch
	}
	return nil
}

func (x *IdentityKey) GetSigningFingerprintMatch() *StringMatcher {
	if x != nil {
		return x.SigningFingerprintMatch
	}
	return nil
}

// IdentityRef represents a reference to an identity. At the policy level, a
// ref allows to have a common definitions that can be reused by all policies
// in a set.
type IdentityRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityRef) Reset() {
	*x = IdentityRef{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityRef) ProtoMessage() {}

func (x *IdentityRef) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityRef.ProtoReflect.Descriptor instead.
func (*IdentityRef) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *IdentityRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// IdentitySpiffe represents a SPIFFE workload identity.
//
// svid carries the canonical SPIFFE ID URI (spiffe://<trust-domain><path>).
// This matches the native SPIFFE representation and what verifiers surface
// in VerificationResult.VerifiedIdentity.SubjectAlternativeName.
//
// trust_roots inlines the PEM-encoded SPIRE upstream CA root(s) used to
// validate the SVID chain, analogous to IdentityKey.data. Unlike the
// sigstore flow there is no universal trust-root registry for SPIFFE, so
// the policy must carry (or reference) the anchor itself.
type IdentitySpiffe struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Svid       string                 `protobuf:"bytes,1,opt,name=svid,proto3" json:"svid,omitempty"`
	TrustRoots string                 `protobuf:"bytes,2,opt,name=trust_roots,json=trustRoots,proto3" json:"trust_roots,omitempty"`
	// Convenience per-field matchers. svid_match matches against the
	// full SVID URI; trust_domain_match and path_match apply to the
	// decomposed components parsed from the signer's svid at eval time.
	// No trust_roots_match: trust anchors are cryptographic material.
	SvidMatch        *StringMatcher `protobuf:"bytes,3,opt,name=svid_match,json=svidMatch,proto3" json:"svid_match,omitempty"`
	TrustDomainMatch *StringMatcher `protobuf:"bytes,4,opt,name=trust_domain_match,json=trustDomainMatch,proto3" json:"trust_domain_match,omitempty"`
	PathMatch        *StringMatcher `protobuf:"bytes,5,opt,name=path_match,json=pathMatch,proto3" json:"path_match,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IdentitySpiffe) Reset() {
	*x = IdentitySpiffe{}
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentitySpiffe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentitySpiffe) ProtoMessage() {}

func (x *IdentitySpiffe) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentitySpiffe.ProtoReflect.Descriptor instead.
func (*IdentitySpiffe) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *IdentitySpiffe) GetSvid() string {
	if x != nil {
		return x.Svid
	}
	return ""
}

func (x *IdentitySpiffe) GetTrustRoots() string {
	if x != nil {
		return x.TrustRoots
	}
	return ""
}

func (x *IdentitySpiffe) GetSvidMatch() *StringMatcher {
	if x != nil {
		return x.SvidMatch
	}
	return nil
}

func (x *IdentitySpiffe) GetTrustDomainMatch() *StringMatcher {
	if x != nil {
		return x.TrustDomainMatch
	}
	return nil
}

func (x *IdentitySpiffe) GetPathMatch() *StringMatcher {
	if x != nil {
		return x.PathMatch
	}
	return nil
}

var File_carabiner_signer_v1_identity_proto protoreflect.FileDescriptor

const file_carabiner_signer_v1_identity_proto_rawDesc = "" +
	"\n" +
	"\"carabiner/signer/v1/identity.proto\x12\x13carabiner.signer.v1\x1a!carabiner/signer/v1/matcher.proto\"\xf8\x02\n" +
	"\bIdentity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12F\n" +
	"\bsigstore\x18\x02 \x01(\v2%.carabiner.signer.v1.IdentitySigstoreH\x00R\bsigstore\x88\x01\x01\x127\n" +
	"\x03key\x18\x03 \x01(\v2 .carabiner.signer.v1.IdentityKeyH\x01R\x03key\x88\x01\x01\x127\n" +
	"\x03ref\x18\x04 \x01(\v2 .carabiner.signer.v1.IdentityRefH\x02R\x03ref\x88\x01\x01\x12@\n" +
	"\x06spiffe\x18\x05 \x01(\v2#.carabiner.signer.v1.IdentitySpiffeH\x03R\x06spiffe\x88\x01\x01\x128\n" +
	"\bmatchers\x18\n" +
	" \x03(\v2\x1c.carabiner.signer.v1.MatcherR\bmatchersB\v\n" +
	"\t_sigstoreB\x06\n" +
	"\x04_keyB\x06\n" +
	"\x04_refB\t\n" +
	"\a_spiffe\"\xa4\x06\n" +
	"\x10IdentitySigstore\x12\x17\n" +
	"\x04mode\x18\x01 \x01(\tH\x00R\x04mode\x88\x01\x01\x12\x16\n" +
	"\x06issuer\x18\x02 \x01(\tR\x06issuer\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\x12E\n" +
	"\fissuer_match\x18\x04 \x01(\v2\".carabiner.signer.v1.StringMatcherR\vissuerMatch\x12I\n" +
	"\x0eidentity_match\x18\x05 \x01(\v2\".carabiner.signer.v1.StringMatcherR\ridentityMatch\x122\n" +
	"\x15source_repository_uri\x18\x06 \x01(\tR\x13sourceRepositoryUri\x12a\n" +
	"\x1bsource_repository_uri_match\x18\a \x01(\v2\".carabiner.signer.v1.StringMatcherR\x18sourceRepositoryUriMatch\x12(\n" +
	"\x10build_config_uri\x18\b \x01(\tR\x0ebuildConfigUri\x12W\n" +
	"\x16build_config_uri_match\x18\t \x01(\v2\".carabiner.signer.v1.StringMatcherR\x13buildConfigUriMatch\x12#\n" +
	"\rbuild_trigger\x18\n" +
	" \x01(\tR\fbuildTrigger\x12R\n" +
	"\x13build_trigger_match\x18\v \x01(\v2\".carabiner.signer.v1.StringMatcherR\x11buildTriggerMatch\x122\n" +
	"\x15source_repository_ref\x18\f \x01(\tR\x13sourceRepositoryRef\x12a\n" +
	"\x1bsource_repository_ref_match\x18\r \x01(\v2\".carabiner.signer.v1.StringMatcherR\x18sourceRepositoryRefMatchB\a\n" +
	"\x05_mode\"\xd8\x02\n" +
	"\vIdentityKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\x12/\n" +
	"\x13signing_fingerprint\x18\x04 \x01(\tR\x12signingFingerprint\x12=\n" +
	"\bid_match\x18\x05 \x01(\v2\".carabiner.signer.v1.StringMatcherR\aidMatch\x12A\n" +
	"\n" +
	"type_match\x18\x06 \x01(\v2\".carabiner.signer.v1.StringMatcherR\ttypeMatch\x12^\n" +
	"\x19signing_fingerprint_match\x18\a \x01(\v2\".carabiner.signer.v1.StringMatcherR\x17signingFingerprintMatch\"\x1d\n" +
	"\vIdentityRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9d\x02\n" +
	"\x0eIdentitySpiffe\x12\x12\n" +
	"\x04svid\x18\x01 \x01(\tR\x04svid\x12\x1f\n" +
	"\vtrust_roots\x18\x02 \x01(\tR\n" +
	"trustRoots\x12A\n" +
	"\n" +
	"svid_match\x18\x03 \x01(\v2\".carabiner.signer.v1.StringMatcherR\tsvidMatch\x12P\n" +
	"\x12trust_domain_match\x18\x04 \x01(\v2\".carabiner.signer.v1.StringMatcherR\x10trustDomainMatch\x12A\n" +
	"\n" +
	"path_match\x18\x05 \x01(\v2\".carabiner.signer.v1.StringMatcherR\tpathMatchB\xbb\x01\n" +
	"\x17com.carabiner.signer.v1B\rIdentityProtoP\x01Z#github.com/policylabs/signer/api/v1\xa2\x02\x03CSX\xaa\x02\x13Carabiner.Signer.V1\xca\x02\x13Carabiner\\Signer\\V1\xe2\x02\x1fCarabiner\\Signer\\V1\\GPBMetadata\xea\x02\x15Carabiner::Signer::V1b\x06proto3"

var (
	file_carabiner_signer_v1_identity_proto_rawDescOnce sync.Once
	file_carabiner_signer_v1_identity_proto_rawDescData []byte
)

func file_carabiner_signer_v1_identity_proto_rawDescGZIP() []byte {
	file_carabiner_signer_v1_identity_proto_rawDescOnce.Do(func() {
		file_carabiner_signer_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_signer_v1_identity_proto_rawDesc), len(file_carabiner_signer_v1_identity_proto_rawDesc)))
	})
	return file_carabiner_signer_v1_identity_proto_rawDescData
}

var file_carabiner_signer_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_carabiner_signer_v1_identity_proto_goTypes = []any{
	(*Identity)(nil),         // 0: carabiner.signer.v1.Identity
	(*IdentitySigstore)(nil), // 1: carabiner.signer.v1.IdentitySigstore
	(*IdentityKey)(nil),      // 2: carabiner.signer.v1.IdentityKey
	(*IdentityRef)(nil),      // 3: carabiner.signer.v1.IdentityRef
	(*IdentitySpiffe)(nil),   // 4: carabiner.signer.v1.IdentitySpiffe
	(*Matcher)(nil),          // 5: carabiner.signer.v1.Matcher
	(*StringMatcher)(nil),    // 6: carabiner.signer.v1.StringMatcher
}
var file_carabiner_signer_v1_identity_proto_depIdxs = []int32{
	1,  // 0: carabiner.signer.v1.Identity.sigstore:type_name -> carabiner.signer.v1.IdentitySigstore
	2,  // 1: carabiner.signer.v1.Identity.key:type_name -> carabiner.signer.v1.IdentityKey
	3,  // 2: carabiner.signer.v1.Identity.ref:type_name -> carabiner.signer.v1.IdentityRef
	4,  // 3: carabiner.signer.v1.Identity.spiffe:type_name -> carabiner.signer.v1.IdentitySpiffe
	5,  // 4: carabiner.signer.v1.Identity.matchers:type_name -> carabiner.signer.v1.Matcher
	6,  // 5: carabiner.signer.v1.IdentitySigstore.issuer_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 6: carabiner.signer.v1.IdentitySigstore.identity_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 7: carabiner.signer.v1.IdentitySigstore.source_repository_uri_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 8: carabiner.signer.v1.IdentitySigstore.build_config_uri_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 9: carabiner.signer.v1.IdentitySigstore.build_trigger_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 10: carabiner.signer.v1.IdentitySigstore.source_repository_ref_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 11: carabiner.signer.v1.IdentityKey.id_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 12: carabiner.signer.v1.IdentityKey.type_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 13: carabiner.signer.v1.IdentityKey.signing_fingerprint_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 14: carabiner.signer.v1.IdentitySpiffe.svid_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 15: carabiner.signer.v1.IdentitySpiffe.trust_domain_match:type_name -> carabiner.signer.v1.StringMatcher
	6,  // 16: carabiner.signer.v1.IdentitySpiffe.path_match:type_name -> carabiner.signer.v1.StringMatcher
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_carabiner_signer_v1_identity_proto_init() }
func file_carabiner_signer_v1_identity_proto_init() {
	if File_carabiner_signer_v1_identity_proto != nil {
		return
	}
	file_carabiner_signer_v1_matcher_proto_init()
	file_carabiner_signer_v1_identity_proto_msgTypes[0].OneofWrappers = []any{}
	file_carabiner_signer_v1_identity_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_signer_v1_identity_proto_rawDesc), len(file_carabiner_signer_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_signer_v1_identity_proto_goTypes,
		DependencyIndexes: file_carabiner_signer_v1_identity_proto_depIdxs,
		MessageInfos:      file_carabiner_signer_v1_identity_proto_msgTypes,
	}.Build()
	File_carabiner_signer_v1_identity_proto = out.File
	file_carabiner_signer_v1_identity_proto_goTypes = nil
	file_carabiner_signer_v1_identity_proto_depIdxs = nil
}
