// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: carabiner/signer/v1/matcher.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Matcher is a single constraint on a field of the selected Identity
// variant. The field selector names a sub-field using dotted notation:
//
//	"principal"                  // the whole principal string
//	"sigstore.issuer"
//	"sigstore.identity"
//	"sigstore.source_repository_uri"
//	"sigstore.build_config_uri"
//	"sigstore.build_trigger"
//	"sigstore.source_repository_ref"
//	"key.id"
//	"key.type"
//	"key.signing_fingerprint"
//	"spiffe.trust_domain"
//	"spiffe.path"
//
// The oneof `kind` is designed to grow additively. Adding new matcher
// kinds (Int, Duration, List, Bool, composite and/or/not) is a proto
// change, never a breaking one.
type Matcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Field string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Matcher_String_
	Kind          isMatcher_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matcher) Reset() {
	*x = Matcher{}
	mi := &file_carabiner_signer_v1_matcher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matcher) ProtoMessage() {}

func (x *Matcher) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_matcher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matcher.ProtoReflect.Descriptor instead.
func (*Matcher) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_matcher_proto_rawDescGZIP(), []int{0}
}

func (x *Matcher) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Matcher) GetKind() isMatcher_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Matcher) GetString_() *StringMatcher {
	if x != nil {
		if x, ok := x.Kind.(*Matcher_String_); ok {
			return x.String_
		}
	}
	return nil
}

type isMatcher_Kind interface {
	isMatcher_Kind()
}

type Matcher_String_ struct {
	String_ *StringMatcher `protobuf:"bytes,2,opt,name=string,proto3,oneof"`
}

func (*Matcher_String_) isMatcher_Kind() {}

// StringMatcher is the concrete matcher for string-valued fields.
// Exactly one of the `kind` variants must be set, unless from_context is used.
type StringMatcher struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*StringMatcher_Exact
	//	*StringMatcher_Regex
	//	*StringMatcher_Prefix
	//	*StringMatcher_Glob
	Kind            isStringMatcher_Kind `protobuf_oneof:"kind"`
	CaseInsensitive bool                 `protobuf:"varint,5,opt,name=case_insensitive,json=caseInsensitive,proto3" json:"case_insensitive,omitempty"`
	// from_context names a value the matching caller (e.g. ampel) resolves into
	// this matcher as an exact match before use. Mutually exclusive with a
	// `kind`. If it reaches matching unresolved, the match fails closed.
	FromContext   string `protobuf:"bytes,6,opt,name=from_context,json=fromContext,proto3" json:"from_context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringMatcher) Reset() {
	*x = StringMatcher{}
	mi := &file_carabiner_signer_v1_matcher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringMatcher) ProtoMessage() {}

func (x *StringMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_signer_v1_matcher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringMatcher.ProtoReflect.Descriptor instead.
func (*StringMatcher) Descriptor() ([]byte, []int) {
	return file_carabiner_signer_v1_matcher_proto_rawDescGZIP(), []int{1}
}

func (x *StringMatcher) GetKind() isStringMatcher_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *StringMatcher) GetExact() string {
	if x != nil {
		if x, ok := x.Kind.(*StringMatcher_Exact); ok {
			return x.Exact
		}
	}
	return ""
}

func (x *StringMatcher) GetRegex() string {
	if x != nil {
		if x, ok := x.Kind.(*StringMatcher_Regex); ok {
			return x.Regex
		}
	}
	return ""
}

func (x *StringMatcher) GetPrefix() string {
	if x != nil {
		if x, ok := x.Kind.(*StringMatcher_Prefix); ok {
			return x.Prefix
		}
	}
	return ""
}

func (x *StringMatcher) GetGlob() string {
	if x != nil {
		if x, ok := x.Kind.(*StringMatcher_Glob); ok {
			return x.Glob
		}
	}
	return ""
}

func (x *StringMatcher) GetCaseInsensitive() bool {
	if x != nil {
		return x.CaseInsensitive
	}
	return false
}

func (x *StringMatcher) GetFromContext() string {
	if x != nil {
		return x.FromContext
	}
	return ""
}

type isStringMatcher_Kind interface {
	isStringMatcher_Kind()
}

type StringMatcher_Exact struct {
	Exact string `protobuf:"bytes,1,opt,name=exact,proto3,oneof"`
}

type StringMatcher_Regex struct {
	Regex string `protobuf:"bytes,2,opt,name=regex,proto3,oneof"` // anchored to the full input at compile time
}

type StringMatcher_Prefix struct {
	Prefix string `protobuf:"bytes,3,opt,name=prefix,proto3,oneof"`
}

type StringMatcher_Glob struct {
	Glob string `protobuf:"bytes,4,opt,name=glob,proto3,oneof"` // shell-style glob (*, ?, [...])
}

func (*StringMatcher_Exact) isStringMatcher_Kind() {}

func (*StringMatcher_Regex) isStringMatcher_Kind() {}

func (*StringMatcher_Prefix) isStringMatcher_Kind() {}

func (*StringMatcher_Glob) isStringMatcher_Kind() {}

var File_carabiner_signer_v1_matcher_proto protoreflect.FileDescriptor

const file_carabiner_signer_v1_matcher_proto_rawDesc = "" +
	"\n" +
	"!carabiner/signer/v1/matcher.proto\x12\x13carabiner.signer.v1\"e\n" +
	"\aMatcher\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12<\n" +
	"\x06string\x18\x02 \x01(\v2\".carabiner.signer.v1.StringMatcherH\x00R\x06stringB\x06\n" +
	"\x04kind\"\xc5\x01\n" +
	"\rStringMatcher\x12\x16\n" +
	"\x05exact\x18\x01 \x01(\tH\x00R\x05exact\x12\x16\n" +
	"\x05regex\x18\x02 \x01(\tH\x00R\x05regex\x12\x18\n" +
	"\x06prefix\x18\x03 \x01(\tH\x00R\x06prefix\x12\x14\n" +
	"\x04glob\x18\x04 \x01(\tH\x00R\x04glob\x12)\n" +
	"\x10case_insensitive\x18\x05 \x01(\bR\x0fcaseInsensitive\x12!\n" +
	"\ffrom_context\x18\x06 \x01(\tR\vfromContextB\x06\n" +
	"\x04kindB\xba\x01\n" +
	"\x17com.carabiner.signer.v1B\fMatcherProtoP\x01Z#github.com/policylabs/signer/api/v1\xa2\x02\x03CSX\xaa\x02\x13Carabiner.Signer.V1\xca\x02\x13Carabiner\\Signer\\V1\xe2\x02\x1fCarabiner\\Signer\\V1\\GPBMetadata\xea\x02\x15Carabiner::Signer::V1b\x06proto3"

var (
	file_carabiner_signer_v1_matcher_proto_rawDescOnce sync.Once
	file_carabiner_signer_v1_matcher_proto_rawDescData []byte
)

func file_carabiner_signer_v1_matcher_proto_rawDescGZIP() []byte {
	file_carabiner_signer_v1_matcher_proto_rawDescOnce.Do(func() {
		file_carabiner_signer_v1_matcher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_signer_v1_matcher_proto_rawDesc), len(file_carabiner_signer_v1_matcher_proto_rawDesc)))
	})
	return file_carabiner_signer_v1_matcher_proto_rawDescData
}

var file_carabiner_signer_v1_matcher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_carabiner_signer_v1_matcher_proto_goTypes = []any{
	(*Matcher)(nil),       // 0: carabiner.signer.v1.Matcher
	(*StringMatcher)(nil), // 1: carabiner.signer.v1.StringMatcher
}
var file_carabiner_signer_v1_matcher_proto_depIdxs = []int32{
	1, // 0: carabiner.signer.v1.Matcher.string:type_name -> carabiner.signer.v1.StringMatcher
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_carabiner_signer_v1_matcher_proto_init() }
func file_carabiner_signer_v1_matcher_proto_init() {
	if File_carabiner_signer_v1_matcher_proto != nil {
		return
	}
	file_carabiner_signer_v1_matcher_proto_msgTypes[0].OneofWrappers = []any{
		(*Matcher_String_)(nil),
	}
	file_carabiner_signer_v1_matcher_proto_msgTypes[1].OneofWrappers = []any{
		(*StringMatcher_Exact)(nil),
		(*StringMatcher_Regex)(nil),
		(*StringMatcher_Prefix)(nil),
		(*StringMatcher_Glob)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_signer_v1_matcher_proto_rawDesc), len(file_carabiner_signer_v1_matcher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_signer_v1_matcher_proto_goTypes,
		DependencyIndexes: file_carabiner_signer_v1_matcher_proto_depIdxs,
		MessageInfos:      file_carabiner_signer_v1_matcher_proto_msgTypes,
	}.Build()
	File_carabiner_signer_v1_matcher_proto = out.File
	file_carabiner_signer_v1_matcher_proto_goTypes = nil
	file_carabiner_signer_v1_matcher_proto_depIdxs = nil
}
