---
name: SLSA Source
on:
  push:
    branches: [ "main" ]
    tags: ['**']
permissions: {}

jobs:
  # Whenever new source is pushed recompute the slsa source information.
  generate-provenance:
    permissions:
      contents: write # needed for storing the vsa in the repo.
      id-token: write # meeded to mint yokens for signing
    uses: slsa-framework/actions/.github/workflows/compute_slsa_source.yml@44d5bd303981daa33ed81605c33a41ca23c9b0d1 # main
    with:
      allow-merge-commits: true
