---
name: SLSA Source
on:
  push:
    branches: [ "main" ]
    tags: ['**']
permissions: {}

jobs:
  # Whenever new source is pushed recompute the slsa source information.
  generate-provenance:
    permissions:
      contents: write # needed for storing the vsa in the repo.
      id-token: write # meeded to mint yokens for signing
    uses: slsa-framework/actions/.github/workflows/compute_slsa_source.yml@078463f1155c9295ba9e1b41d49ee2623b4415aa # main
    with:
      allow-merge-commits: true
